### ISSUE TITLE
iTerm Theme?

### ISSUE THREAD

**Issue by ashtonlance** [barjoio/anirak#3]
Not really an issue.

But I love this theme! Have you got an iTerm2 theme handy?

**Comment by barjoio** [comment]
Hey thanks, I'm glad you're enjoying the theme.

[Here](https://github.com/barjoio/anirak/blob/master/other/iterm2/theme.xml) is the iTerm2 theme. I'm not able to verify that it works correctly as I'm not on a Mac, but please do let me know if you encounter any issues and we can try get them fixed.

Cheers
